### ISSUE TITLE
"Package unavailable" but it was just installed

### ISSUE THREAD

**Issue by Fuco1** [emacs-eask/cli#158] opened 2023-03-11 19:00 UTC
https://github.com/emacs-elsa/Elsa/actions/runs/4393705151/jobs/7694278385

![image](https://user-images.githubusercontent.com/2664959/224506766-8b4cde8c-8b47-40a5-a10e-1077c9087c59.png)

**Comment by jcs090218** [comment] 2023-03-11 19:40
Yeah, that's something odd between the version base and the timestamp base. I don't know why package.el is reporting this error, I will need to further investigate it. BTW, We may not resolve this issue since the error came from package.el, so it should be resolved in upstream.

The workaround is to lower the version you specified in you package file. It may sounds weird, but when users install package from MELPA, you will always get the latest version.

**Comment by Fuco1** [comment] 2023-03-11 21:04
Well, you always get the latest version.  I guess the version constraint only prevents you from loading the package without updating all dependencies (?).  Honestly package.el is pretty dumb :D

**Comment by jcs090218** [comment] 2023-03-11 21:09
I think I've found the culprit,

https://github.com/emacs-elsa/Elsa/blob/master/elsa.el#L9

it should be:

```diff
- ;; Package-Requires: ((emacs "26.1") (trinary "0") (f "0") (dash "2.14") (cl-lib "0.3") (lsp-mode "0") (ansi "0") ("async" "1.9.7"))
+ ;; Package-Requires: ((emacs "26.1") (trinary "0") (f "0") (dash "2.14") (cl-lib "0.3") (lsp-mode "0") (ansi "0") (async "1.9.7"))
```

Remove the extra double quotes, then it works!

**Comment by jcs090218** [comment] 2023-03-11 21:14
`package.el` is kinda dumb to version base (MELPA). That may be why. Suppose something goes wrong with `package.el` installing package from MELPA, then it's MELPA's issue since they promised to be fully compatible with ELPA, etc. Another option is MELPA-STABLE. 😅

**Comment by jcs090218** [comment] 2023-03-14 18:45
I think the issue is resolved. Therefore close this issue. :)

**Closed** 2023-03-14 18:45 UTC
